export const allAirports = [
    // --- INDIA ---
    { id: 1, name: "New Delhi", code: "DEL", country: "India", type: "domestic" },
    { id: 2, name: "Mumbai", code: "BOM", country: "India", type: "domestic" },
    { id: 3, name: "Bangalore", code: "BLR", country: "India", type: "domestic" },
    { id: 4, name: "Chennai", code: "MAA", country: "India", type: "domestic" },
    { id: 5, name: "Kolkata", code: "CCU", country: "India", type: "domestic" },
    { id: 6, name: "Hyderabad", code: "HYD", country: "India", type: "domestic" },
    { id: 7, name: "Ahmedabad", code: "AMD", country: "India", type: "domestic" },
    { id: 8, name: "Goa Dabolim", code: "GOI", country: "India", type: "domestic" },
    { id: 9, name: "Jaipur", code: "JAI", country: "India", type: "domestic" },
    { id: 10, name: "Lucknow", code: "LKO", country: "India", type: "domestic" },
    { id: 11, name: "Pune", code: "PNQ", country: "India", type: "domestic" },
    { id: 12, name: "Kochi", code: "COK", country: "India", type: "domestic" },
    { id: 13, name: "Thiruvananthapuram", code: "TRV", country: "India", type: "domestic" },
    { id: 14, name: "Guwahati", code: "GAU", country: "India", type: "domestic" },
    { id: 15, name: "Varanasi", code: "VNS", country: "India", type: "domestic" },
    { id: 16, name: "Amritsar", code: "ATQ", country: "India", type: "domestic" },
    { id: 17, name: "Bhopal", code: "BHO", country: "India", type: "domestic" },
    { id: 18, name: "Indore", code: "IDR", country: "India", type: "domestic" },
    { id: 19, name: "Patna", code: "PAT", country: "India", type: "domestic" },
    { id: 20, name: "Bhubaneswar", code: "BBI", country: "India", type: "domestic" },
    { id: 21, name: "Nagpur", code: "NAG", country: "India", type: "domestic" },
    { id: 22, name: "Vadodara", code: "BDQ", country: "India", type: "domestic" },
    { id: 23, name: "Surat", code: "STV", country: "India", type: "domestic" },
    { id: 24, name: "Visakhapatnam", code: "VTZ", country: "India", type: "domestic" },
    { id: 25, name: "Coimbatore", code: "CJB", country: "India", type: "domestic" },
    { id: 26, name: "Mangalore", code: "IXE", country: "India", type: "domestic" },
    { id: 27, name: "Madurai", code: "IXM", country: "India", type: "domestic" },
    { id: 28, name: "Tiruchirappalli", code: "TRZ", country: "India", type: "domestic" },
    { id: 29, name: "Dehradun", code: "DED", country: "India", type: "domestic" },
    { id: 30, name: "Srinagar", code: "SXR", country: "India", type: "domestic" },
    { id: 31, name: "Chandigarh", code: "IXC", country: "India", type: "domestic" },
    { id: 32, name: "Aurangabad", code: "IXU", country: "India", type: "domestic" },
    { id: 33, name: "Jammu", code: "IXJ", country: "India", type: "domestic" },
    { id: 34, name: "Ranchi", code: "IXR", country: "India", type: "domestic" },
    { id: 35, name: "Bagdogra", code: "IXB", country: "India", type: "domestic" },
    { id: 36, name: "Port Blair", code: "IXZ", country: "India", type: "domestic" },
    { id: 37, name: "Agartala", code: "IXA", country: "India", type: "domestic" },
    { id: 38, name: "Allahabad", code: "IXD", country: "India", type: "domestic" },
    { id: 39, name: "Belgaum", code: "IXG", country: "India", type: "domestic" },
    { id: 40, name: "Kailashahar", code: "IXH", country: "India", type: "domestic" },
    { id: 41, name: "Lilabari", code: "IXI", country: "India", type: "domestic" },
    { id: 42, name: "Keshod", code: "IXK", country: "India", type: "domestic" },
    { id: 43, name: "Leh", code: "IXL", country: "India", type: "domestic" },
    { id: 44, name: "Khowai", code: "IXN", country: "India", type: "domestic" },
    { id: 45, name: "Pathankot", code: "IXP", country: "India", type: "domestic" },
    { id: 46, name: "Kamalpur", code: "IXQ", country: "India", type: "domestic" },
    { id: 47, name: "Silchar", code: "IXS", country: "India", type: "domestic" },
    { id: 48, name: "Pasighat", code: "IXT", country: "India", type: "domestic" },
    { id: 49, name: "Along", code: "IXV", country: "India", type: "domestic" },
    { id: 50, name: "Jamshedpur", code: "IXW", country: "India", type: "domestic" },
    { id: 51, name: "Kandla", code: "IXY", country: "India", type: "domestic" },
    { id: 52, name: "Manohar International (Mopa)", code: "GOX", country: "India", type: "domestic" },
    { id: 53, name: "Jodhpur", code: "JDH", country: "India", type: "domestic" },
    { id: 54, name: "Udaipur", code: "UDR", country: "India", type: "domestic" },
    { id: 55, name: "Rajkot", code: "RAJ", country: "India", type: "domestic" },
    { id: 56, name: "Shimla", code: "SLV", country: "India", type: "domestic" },
    { id: 57, name: "Dharamsala", code: "DHM", country: "India", type: "domestic" },
    { id: 58, name: "Kullu", code: "KUU", country: "India", type: "domestic" },

    // --- UNITED STATES ---
    { id: 100, name: "Atlanta", code: "ATL", country: "United States", type: "international" },
    { id: 101, name: "Los Angeles", code: "LAX", country: "United States", type: "international" },
    { id: 102, name: "Chicago O'Hare", code: "ORD", country: "United States", type: "international" },
    { id: 103, name: "Dallas/Fort Worth", code: "DFW", country: "United States", type: "international" },
    { id: 104, name: "Denver", code: "DEN", country: "United States", type: "international" },
    { id: 105, name: "New York JFK", code: "JFK", country: "United States", type: "international" },
    { id: 106, name: "San Francisco", code: "SFO", country: "United States", type: "international" },
    { id: 107, name: "Seattle", code: "SEA", country: "United States", type: "international" },
    { id: 108, name: "Las Vegas", code: "LAS", country: "United States", type: "international" },
    { id: 109, name: "Orlando", code: "MCO", country: "United States", type: "international" },
    { id: 110, name: "Newark", code: "EWR", country: "United States", type: "international" },
    { id: 111, name: "Charlotte", code: "CLT", country: "United States", type: "international" },
    { id: 112, name: "Phoenix", code: "PHX", country: "United States", type: "international" },
    { id: 113, name: "Houston Intercontinental", code: "IAH", country: "United States", type: "international" },
    { id: 114, name: "Miami", code: "MIA", country: "United States", type: "international" },
    { id: 115, name: "Boston", code: "BOS", country: "United States", type: "international" },
    { id: 116, name: "Minneapolis", code: "MSP", country: "United States", type: "international" },
    { id: 117, name: "Detroit", code: "DTW", country: "United States", type: "international" },
    { id: 118, name: "Philadelphia", code: "PHL", country: "United States", type: "international" },
    { id: 119, name: "Salt Lake City", code: "SLC", country: "United States", type: "international" },
    { id: 120, name: "Washington Dulles", code: "IAD", country: "United States", type: "international" },
    { id: 121, name: "Washington Reagan", code: "DCA", country: "United States", type: "international" },
    { id: 122, name: "San Diego", code: "SAN", country: "United States", type: "international" },
    { id: 123, name: "Baltimore", code: "BWI", country: "United States", type: "international" },
    { id: 124, name: "Tampa", code: "TPA", country: "United States", type: "international" },
    { id: 125, name: "Fort Lauderdale", code: "FLL", country: "United States", type: "international" },
    { id: 126, name: "Portland", code: "PDX", country: "United States", type: "international" },
    { id: 127, name: "Honolulu", code: "HNL", country: "United States", type: "international" },
    { id: 128, name: "Chicago Midway", code: "MDW", country: "United States", type: "international" },
    { id: 129, name: "Austin", code: "AUS", country: "United States", type: "international" },
    { id: 130, name: "Nashville", code: "BNA", country: "United States", type: "international" },
    { id: 131, name: "San Jose", code: "SJC", country: "United States", type: "international" },
    { id: 132, name: "St. Louis", code: "STL", country: "United States", type: "international" },
    { id: 133, name: "Oakland", code: "OAK", country: "United States", type: "international" },
    { id: 134, name: "Pittsburgh", code: "PIT", country: "United States", type: "international" },
    { id: 135, name: "New Orleans", code: "MSY", country: "United States", type: "international" },
    { id: 136, name: "Raleigh-Durham", code: "RDU", country: "United States", type: "international" },
    { id: 137, name: "Sacramento", code: "SMF", country: "United States", type: "international" },
    { id: 138, name: "Indianapolis", code: "IND", country: "United States", type: "international" },
    { id: 139, name: "Orange County", code: "SNA", country: "United States", type: "international" },
    { id: 140, name: "Kansas City", code: "MCI", country: "United States", type: "international" },
    { id: 141, name: "San Antonio", code: "SAT", country: "United States", type: "international" },
    { id: 142, name: "Cleveland", code: "CLE", country: "United States", type: "international" },
    { id: 143, name: "Columbus", code: "CMH", country: "United States", type: "international" },

    // --- CANADA ---
    { id: 200, name: "Toronto Pearson", code: "YYZ", country: "Canada", type: "international" },
    { id: 201, name: "Vancouver", code: "YVR", country: "Canada", type: "international" },
    { id: 202, name: "Montreal-Trudeau", code: "YUL", country: "Canada", type: "international" },
    { id: 203, name: "Calgary", code: "YYC", country: "Canada", type: "international" },
    { id: 204, name: "Edmonton", code: "YEG", country: "Canada", type: "international" },
    { id: 205, name: "Ottawa", code: "YOW", country: "Canada", type: "international" },
    { id: 206, name: "Winnipeg", code: "YWG", country: "Canada", type: "international" },
    { id: 207, name: "Halifax", code: "YHZ", country: "Canada", type: "international" },
    { id: 208, name: "Victoria", code: "YYJ", country: "Canada", type: "international" },
    { id: 209, name: "St. John's", code: "YYT", country: "Canada", type: "international" },

    // --- UNITED KINGDOM ---
    { id: 300, name: "London Heathrow", code: "LHR", country: "United Kingdom", type: "international" },
    { id: 301, name: "London Gatwick", code: "LGW", country: "United Kingdom", type: "international" },
    { id: 302, name: "London Stansted", code: "STN", country: "United Kingdom", type: "international" },
    { id: 303, name: "London Luton", code: "LTN", country: "United Kingdom", type: "international" },
    { id: 304, name: "Manchester", code: "MAN", country: "United Kingdom", type: "international" },
    { id: 305, name: "Edinburgh", code: "EDI", country: "United Kingdom", type: "international" },
    { id: 306, name: "Birmingham", code: "BHX", country: "United Kingdom", type: "international" },
    { id: 307, name: "Glasgow", code: "GLA", country: "United Kingdom", type: "international" },
    { id: 308, name: "Bristol", code: "BRS", country: "United Kingdom", type: "international" },
    { id: 309, name: "Belfast International", code: "BFS", country: "United Kingdom", type: "international" },
    { id: 310, name: "Newcastle", code: "NCL", country: "United Kingdom", type: "international" },
    { id: 311, name: "Liverpool", code: "LPL", country: "United Kingdom", type: "international" },

    // --- EUROPE ---
    { id: 400, name: "Paris Charles de Gaulle", code: "CDG", country: "France", type: "international" },
    { id: 401, name: "Paris Orly", code: "ORY", country: "France", type: "international" },
    { id: 402, name: "Frankfurt", code: "FRA", country: "Germany", type: "international" },
    { id: 403, name: "Munich", code: "MUC", country: "Germany", type: "international" },
    { id: 404, name: "Amsterdam Schiphol", code: "AMS", country: "Netherlands", type: "international" },
    { id: 405, name: "Madrid Barajas", code: "MAD", country: "Spain", type: "international" },
    { id: 406, name: "Barcelona El Prat", code: "BCN", country: "Spain", type: "international" },
    { id: 407, name: "Rome Fiumicino", code: "FCO", country: "Italy", type: "international" },
    { id: 408, name: "Milan Malpensa", code: "MXP", country: "Italy", type: "international" },
    { id: 409, name: "Zurich", code: "ZRH", country: "Switzerland", type: "international" },
    { id: 410, name: "Geneva", code: "GVA", country: "Switzerland", type: "international" },
    { id: 411, name: "Vienna", code: "VIE", country: "Austria", type: "international" },
    { id: 412, name: "Copenhagen", code: "CPH", country: "Denmark", type: "international" },
    { id: 413, name: "Stockholm Arlanda", code: "ARN", country: "Sweden", type: "international" },
    { id: 414, name: "Oslo Gardermoen", code: "OSL", country: "Norway", type: "international" },
    { id: 415, name: "Helsinki", code: "HEL", country: "Finland", type: "international" },
    { id: 416, name: "Dublin", code: "DUB", country: "Ireland", type: "international" },
    { id: 417, name: "Brussels", code: "BRU", country: "Belgium", type: "international" },
    { id: 418, name: "Lisbon", code: "LIS", country: "Portugal", type: "international" },
    { id: 419, name: "Athens", code: "ATH", country: "Greece", type: "international" },
    { id: 420, name: "Prague", code: "PRG", country: "Czech Republic", type: "international" },
    { id: 421, name: "Warsaw", code: "WAW", country: "Poland", type: "international" },
    { id: 422, name: "Budapest", code: "BUD", country: "Hungary", type: "international" },
    { id: 423, name: "Istanbul", code: "IST", country: "Turkey", type: "international" },
    { id: 424, name: "Istanbul Sabiha Gökçen", code: "SAW", country: "Turkey", type: "international" },
    { id: 425, name: "Berlin Brandenburg", code: "BER", country: "Germany", type: "international" },
    { id: 426, name: "Nice Côte d'Azur", code: "NCE", country: "France", type: "international" },
    { id: 427, name: "Venice Marco Polo", code: "VCE", country: "Italy", type: "international" },

    // --- MIDDLE EAST ---
    { id: 500, name: "Dubai", code: "DXB", country: "UAE", type: "international" },
    { id: 501, name: "Dubai World Central", code: "DWC", country: "UAE", type: "international" },
    { id: 502, name: "Abu Dhabi", code: "AUH", country: "UAE", type: "international" },
    { id: 503, name: "Doha Hamad", code: "DOH", country: "Qatar", type: "international" },
    { id: 504, name: "Riyadh", code: "RUH", country: "Saudi Arabia", type: "international" },
    { id: 505, name: "Jeddah", code: "JED", country: "Saudi Arabia", type: "international" },
    { id: 506, name: "Kuwait International", code: "KWI", country: "Kuwait", type: "international" },
    { id: 507, name: "Muscat", code: "MCT", country: "Oman", type: "international" },
    { id: 508, name: "Bahrain", code: "BAH", country: "Bahrain", type: "international" },
    { id: 509, name: "Tel Aviv Ben Gurion", code: "TLV", country: "Israel", type: "international" },
    { id: 510, name: "Amman Queen Alia", code: "AMM", country: "Jordan", type: "international" },

    // --- ASIA PACIFIC ---
    { id: 600, name: "Singapore Changi", code: "SIN", country: "Singapore", type: "international" },
    { id: 601, name: "Hong Kong", code: "HKG", country: "Hong Kong", type: "international" },
    { id: 602, name: "Tokyo Haneda", code: "HND", country: "Japan", type: "international" },
    { id: 603, name: "Tokyo Narita", code: "NRT", country: "Japan", type: "international" },
    { id: 604, name: "Seoul Incheon", code: "ICN", country: "South Korea", type: "international" },
    { id: 605, name: "Bangkok Suvarnabhumi", code: "BKK", country: "Thailand", type: "international" },
    { id: 606, name: "Bangkok Don Mueang", code: "DMK", country: "Thailand", type: "international" },
    { id: 607, name: "Kuala Lumpur", code: "KUL", country: "Malaysia", type: "international" },
    { id: 608, name: "Jakarta Soekarno-Hatta", code: "CGK", country: "Indonesia", type: "international" },
    { id: 609, name: "Ho Chi Minh City", code: "SGN", country: "Vietnam", type: "international" },
    { id: 610, name: "Hanoi", code: "HAN", country: "Vietnam", type: "international" },
    { id: 611, name: "Manila", code: "MNL", country: "Philippines", type: "international" },
    { id: 612, name: "Beijing Capital", code: "PEK", country: "China", type: "international" },
    { id: 613, name: "Beijing Daxing", code: "PKX", country: "China", type: "international" },
    { id: 614, name: "Shanghai Pudong", code: "PVG", country: "China", type: "international" },
    { id: 615, name: "Shanghai Hongqiao", code: "SHA", country: "China", type: "international" },
    { id: 616, name: "Guangzhou", code: "CAN", country: "China", type: "international" },
    { id: 617, name: "Shenzhen", code: "SZX", country: "China", type: "international" },
    { id: 618, name: "Chengdu Shuangliu", code: "CTU", country: "China", type: "international" },
    { id: 619, name: "Taipei Taoyuan", code: "TPE", country: "Taiwan", type: "international" },
    { id: 620, name: "Sydney", code: "SYD", country: "Australia", type: "international" },
    { id: 621, name: "Melbourne", code: "MEL", country: "Australia", type: "international" },
    { id: 622, name: "Brisbane", code: "BNE", country: "Australia", type: "international" },
    { id: 623, name: "Perth", code: "PER", country: "Australia", type: "international" },
    { id: 624, name: "Auckland", code: "AKL", country: "New Zealand", type: "international" },

    // --- SOUTH AMERICA ---
    { id: 700, name: "São Paulo Guarulhos", code: "GRU", country: "Brazil", type: "international" },
    { id: 701, name: "São Paulo Congonhas", code: "CGH", country: "Brazil", type: "international" },
    { id: 702, name: "Rio de Janeiro Galeão", code: "GIG", country: "Brazil", type: "international" },
    { id: 703, name: "Bogotá", code: "BOG", country: "Colombia", type: "international" },
    { id: 704, name: "Buenos Aires Ezeiza", code: "EZE", country: "Argentina", type: "international" },
    { id: 705, name: "Buenos Aires Jorge Newbery", code: "AEP", country: "Argentina", type: "international" },
    { id: 706, name: "Lima", code: "LIM", country: "Peru", type: "international" },
    { id: 707, name: "Santiago", code: "SCL", country: "Chile", type: "international" },

    // --- AFRICA ---
    { id: 800, name: "Johannesburg OR Tambo", code: "JNB", country: "South Africa", type: "international" },
    { id: 801, name: "Cape Town", code: "CPT", country: "South Africa", type: "international" },
    { id: 802, name: "Cairo", code: "CAI", country: "Egypt", type: "international" },
    { id: 803, name: "Casablanca", code: "CMN", country: "Morocco", type: "international" },
    { id: 804, name: "Addis Ababa", code: "ADD", country: "Ethiopia", type: "international" },
    { id: 805, name: "Nairobi", code: "NBO", country: "Kenya", type: "international" },
    { id: 806, name: "Lagos", code: "LOS", country: "Nigeria", type: "international" },
];
