/**
 * Every country a traveller can hold a passport from: ISO 3166-1, with the
 * three-letter code the airline's passport element (SSR DOCS) takes and the
 * international calling code.
 *
 * The review page offered 50 countries in a list it chose from only on a mouse
 * press, with no typed fallback and no keyboard selection, and the booking
 * chain knew three-letter codes for the same 50. A traveller from anywhere
 * else could not pay for an international trip, and one whose code the chain
 * did not know would have had no passport element and no ticket. One list now
 * serves the page, the phone code and the chain.
 *
 * Dependency-free: the browser and both servers load this file.
 */

// [alpha-2, alpha-3, name, calling code digits]
const TABLE = [
  ['AF', 'AFG', 'Afghanistan', '93'],
  ['AX', 'ALA', 'Åland Islands', '358'],
  ['AL', 'ALB', 'Albania', '355'],
  ['DZ', 'DZA', 'Algeria', '213'],
  ['AS', 'ASM', 'American Samoa', '1'],
  ['AD', 'AND', 'Andorra', '376'],
  ['AO', 'AGO', 'Angola', '244'],
  ['AI', 'AIA', 'Anguilla', '1'],
  ['AQ', 'ATA', 'Antarctica', '672'],
  ['AG', 'ATG', 'Antigua and Barbuda', '1'],
  ['AR', 'ARG', 'Argentina', '54'],
  ['AM', 'ARM', 'Armenia', '374'],
  ['AW', 'ABW', 'Aruba', '297'],
  ['AU', 'AUS', 'Australia', '61'],
  ['AT', 'AUT', 'Austria', '43'],
  ['AZ', 'AZE', 'Azerbaijan', '994'],
  ['BS', 'BHS', 'Bahamas', '1'],
  ['BH', 'BHR', 'Bahrain', '973'],
  ['BD', 'BGD', 'Bangladesh', '880'],
  ['BB', 'BRB', 'Barbados', '1'],
  ['BY', 'BLR', 'Belarus', '375'],
  ['BE', 'BEL', 'Belgium', '32'],
  ['BZ', 'BLZ', 'Belize', '501'],
  ['BJ', 'BEN', 'Benin', '229'],
  ['BM', 'BMU', 'Bermuda', '1'],
  ['BT', 'BTN', 'Bhutan', '975'],
  ['BO', 'BOL', 'Bolivia', '591'],
  ['BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', '599'],
  ['BA', 'BIH', 'Bosnia and Herzegovina', '387'],
  ['BW', 'BWA', 'Botswana', '267'],
  ['BV', 'BVT', 'Bouvet Island', '47'],
  ['BR', 'BRA', 'Brazil', '55'],
  ['IO', 'IOT', 'British Indian Ocean Territory', '246'],
  ['BN', 'BRN', 'Brunei', '673'],
  ['BG', 'BGR', 'Bulgaria', '359'],
  ['BF', 'BFA', 'Burkina Faso', '226'],
  ['BI', 'BDI', 'Burundi', '257'],
  ['CV', 'CPV', 'Cabo Verde', '238'],
  ['KH', 'KHM', 'Cambodia', '855'],
  ['CM', 'CMR', 'Cameroon', '237'],
  ['CA', 'CAN', 'Canada', '1'],
  ['KY', 'CYM', 'Cayman Islands', '1'],
  ['CF', 'CAF', 'Central African Republic', '236'],
  ['TD', 'TCD', 'Chad', '235'],
  ['CL', 'CHL', 'Chile', '56'],
  ['CN', 'CHN', 'China', '86'],
  ['CX', 'CXR', 'Christmas Island', '61'],
  ['CC', 'CCK', 'Cocos (Keeling) Islands', '61'],
  ['CO', 'COL', 'Colombia', '57'],
  ['KM', 'COM', 'Comoros', '269'],
  ['CG', 'COG', 'Congo', '242'],
  ['CD', 'COD', 'Congo (Democratic Republic)', '243'],
  ['CK', 'COK', 'Cook Islands', '682'],
  ['CR', 'CRI', 'Costa Rica', '506'],
  ['CI', 'CIV', "Côte d'Ivoire", '225'],
  ['HR', 'HRV', 'Croatia', '385'],
  ['CU', 'CUB', 'Cuba', '53'],
  ['CW', 'CUW', 'Curaçao', '599'],
  ['CY', 'CYP', 'Cyprus', '357'],
  ['CZ', 'CZE', 'Czechia', '420'],
  ['DK', 'DNK', 'Denmark', '45'],
  ['DJ', 'DJI', 'Djibouti', '253'],
  ['DM', 'DMA', 'Dominica', '1'],
  ['DO', 'DOM', 'Dominican Republic', '1'],
  ['EC', 'ECU', 'Ecuador', '593'],
  ['EG', 'EGY', 'Egypt', '20'],
  ['SV', 'SLV', 'El Salvador', '503'],
  ['GQ', 'GNQ', 'Equatorial Guinea', '240'],
  ['ER', 'ERI', 'Eritrea', '291'],
  ['EE', 'EST', 'Estonia', '372'],
  ['SZ', 'SWZ', 'Eswatini', '268'],
  ['ET', 'ETH', 'Ethiopia', '251'],
  ['FK', 'FLK', 'Falkland Islands', '500'],
  ['FO', 'FRO', 'Faroe Islands', '298'],
  ['FJ', 'FJI', 'Fiji', '679'],
  ['FI', 'FIN', 'Finland', '358'],
  ['FR', 'FRA', 'France', '33'],
  ['GF', 'GUF', 'French Guiana', '594'],
  ['PF', 'PYF', 'French Polynesia', '689'],
  ['TF', 'ATF', 'French Southern Territories', '262'],
  ['GA', 'GAB', 'Gabon', '241'],
  ['GM', 'GMB', 'Gambia', '220'],
  ['GE', 'GEO', 'Georgia', '995'],
  ['DE', 'DEU', 'Germany', '49'],
  ['GH', 'GHA', 'Ghana', '233'],
  ['GI', 'GIB', 'Gibraltar', '350'],
  ['GR', 'GRC', 'Greece', '30'],
  ['GL', 'GRL', 'Greenland', '299'],
  ['GD', 'GRD', 'Grenada', '1'],
  ['GP', 'GLP', 'Guadeloupe', '590'],
  ['GU', 'GUM', 'Guam', '1'],
  ['GT', 'GTM', 'Guatemala', '502'],
  ['GG', 'GGY', 'Guernsey', '44'],
  ['GN', 'GIN', 'Guinea', '224'],
  ['GW', 'GNB', 'Guinea-Bissau', '245'],
  ['GY', 'GUY', 'Guyana', '592'],
  ['HT', 'HTI', 'Haiti', '509'],
  ['HM', 'HMD', 'Heard Island and McDonald Islands', '672'],
  ['VA', 'VAT', 'Holy See (Vatican City)', '39'],
  ['HN', 'HND', 'Honduras', '504'],
  ['HK', 'HKG', 'Hong Kong', '852'],
  ['HU', 'HUN', 'Hungary', '36'],
  ['IS', 'ISL', 'Iceland', '354'],
  ['IN', 'IND', 'India', '91'],
  ['ID', 'IDN', 'Indonesia', '62'],
  ['IR', 'IRN', 'Iran', '98'],
  ['IQ', 'IRQ', 'Iraq', '964'],
  ['IE', 'IRL', 'Ireland', '353'],
  ['IM', 'IMN', 'Isle of Man', '44'],
  ['IL', 'ISR', 'Israel', '972'],
  ['IT', 'ITA', 'Italy', '39'],
  ['JM', 'JAM', 'Jamaica', '1'],
  ['JP', 'JPN', 'Japan', '81'],
  ['JE', 'JEY', 'Jersey', '44'],
  ['JO', 'JOR', 'Jordan', '962'],
  ['KZ', 'KAZ', 'Kazakhstan', '7'],
  ['KE', 'KEN', 'Kenya', '254'],
  ['KI', 'KIR', 'Kiribati', '686'],
  ['KP', 'PRK', 'Korea (North)', '850'],
  ['KR', 'KOR', 'Korea (South)', '82'],
  ['KW', 'KWT', 'Kuwait', '965'],
  ['KG', 'KGZ', 'Kyrgyzstan', '996'],
  ['LA', 'LAO', 'Laos', '856'],
  ['LV', 'LVA', 'Latvia', '371'],
  ['LB', 'LBN', 'Lebanon', '961'],
  ['LS', 'LSO', 'Lesotho', '266'],
  ['LR', 'LBR', 'Liberia', '231'],
  ['LY', 'LBY', 'Libya', '218'],
  ['LI', 'LIE', 'Liechtenstein', '423'],
  ['LT', 'LTU', 'Lithuania', '370'],
  ['LU', 'LUX', 'Luxembourg', '352'],
  ['MO', 'MAC', 'Macao', '853'],
  ['MG', 'MDG', 'Madagascar', '261'],
  ['MW', 'MWI', 'Malawi', '265'],
  ['MY', 'MYS', 'Malaysia', '60'],
  ['MV', 'MDV', 'Maldives', '960'],
  ['ML', 'MLI', 'Mali', '223'],
  ['MT', 'MLT', 'Malta', '356'],
  ['MH', 'MHL', 'Marshall Islands', '692'],
  ['MQ', 'MTQ', 'Martinique', '596'],
  ['MR', 'MRT', 'Mauritania', '222'],
  ['MU', 'MUS', 'Mauritius', '230'],
  ['YT', 'MYT', 'Mayotte', '262'],
  ['MX', 'MEX', 'Mexico', '52'],
  ['FM', 'FSM', 'Micronesia', '691'],
  ['MD', 'MDA', 'Moldova', '373'],
  ['MC', 'MCO', 'Monaco', '377'],
  ['MN', 'MNG', 'Mongolia', '976'],
  ['ME', 'MNE', 'Montenegro', '382'],
  ['MS', 'MSR', 'Montserrat', '1'],
  ['MA', 'MAR', 'Morocco', '212'],
  ['MZ', 'MOZ', 'Mozambique', '258'],
  ['MM', 'MMR', 'Myanmar', '95'],
  ['NA', 'NAM', 'Namibia', '264'],
  ['NR', 'NRU', 'Nauru', '674'],
  ['NP', 'NPL', 'Nepal', '977'],
  ['NL', 'NLD', 'Netherlands', '31'],
  ['NC', 'NCL', 'New Caledonia', '687'],
  ['NZ', 'NZL', 'New Zealand', '64'],
  ['NI', 'NIC', 'Nicaragua', '505'],
  ['NE', 'NER', 'Niger', '227'],
  ['NG', 'NGA', 'Nigeria', '234'],
  ['NU', 'NIU', 'Niue', '683'],
  ['NF', 'NFK', 'Norfolk Island', '672'],
  ['MK', 'MKD', 'North Macedonia', '389'],
  ['MP', 'MNP', 'Northern Mariana Islands', '1'],
  ['NO', 'NOR', 'Norway', '47'],
  ['OM', 'OMN', 'Oman', '968'],
  ['PK', 'PAK', 'Pakistan', '92'],
  ['PW', 'PLW', 'Palau', '680'],
  ['PS', 'PSE', 'Palestine', '970'],
  ['PA', 'PAN', 'Panama', '507'],
  ['PG', 'PNG', 'Papua New Guinea', '675'],
  ['PY', 'PRY', 'Paraguay', '595'],
  ['PE', 'PER', 'Peru', '51'],
  ['PH', 'PHL', 'Philippines', '63'],
  ['PN', 'PCN', 'Pitcairn', '64'],
  ['PL', 'POL', 'Poland', '48'],
  ['PT', 'PRT', 'Portugal', '351'],
  ['PR', 'PRI', 'Puerto Rico', '1'],
  ['QA', 'QAT', 'Qatar', '974'],
  ['RE', 'REU', 'Réunion', '262'],
  ['RO', 'ROU', 'Romania', '40'],
  ['RU', 'RUS', 'Russia', '7'],
  ['RW', 'RWA', 'Rwanda', '250'],
  ['BL', 'BLM', 'Saint Barthélemy', '590'],
  ['SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', '290'],
  ['KN', 'KNA', 'Saint Kitts and Nevis', '1'],
  ['LC', 'LCA', 'Saint Lucia', '1'],
  ['MF', 'MAF', 'Saint Martin (French part)', '590'],
  ['PM', 'SPM', 'Saint Pierre and Miquelon', '508'],
  ['VC', 'VCT', 'Saint Vincent and the Grenadines', '1'],
  ['WS', 'WSM', 'Samoa', '685'],
  ['SM', 'SMR', 'San Marino', '378'],
  ['ST', 'STP', 'Sao Tome and Principe', '239'],
  ['SA', 'SAU', 'Saudi Arabia', '966'],
  ['SN', 'SEN', 'Senegal', '221'],
  ['RS', 'SRB', 'Serbia', '381'],
  ['SC', 'SYC', 'Seychelles', '248'],
  ['SL', 'SLE', 'Sierra Leone', '232'],
  ['SG', 'SGP', 'Singapore', '65'],
  ['SX', 'SXM', 'Sint Maarten (Dutch part)', '1'],
  ['SK', 'SVK', 'Slovakia', '421'],
  ['SI', 'SVN', 'Slovenia', '386'],
  ['SB', 'SLB', 'Solomon Islands', '677'],
  ['SO', 'SOM', 'Somalia', '252'],
  ['ZA', 'ZAF', 'South Africa', '27'],
  ['GS', 'SGS', 'South Georgia and the South Sandwich Islands', '500'],
  ['SS', 'SSD', 'South Sudan', '211'],
  ['ES', 'ESP', 'Spain', '34'],
  ['LK', 'LKA', 'Sri Lanka', '94'],
  ['SD', 'SDN', 'Sudan', '249'],
  ['SR', 'SUR', 'Suriname', '597'],
  ['SJ', 'SJM', 'Svalbard and Jan Mayen', '47'],
  ['SE', 'SWE', 'Sweden', '46'],
  ['CH', 'CHE', 'Switzerland', '41'],
  ['SY', 'SYR', 'Syria', '963'],
  ['TW', 'TWN', 'Taiwan', '886'],
  ['TJ', 'TJK', 'Tajikistan', '992'],
  ['TZ', 'TZA', 'Tanzania', '255'],
  ['TH', 'THA', 'Thailand', '66'],
  ['TL', 'TLS', 'Timor-Leste', '670'],
  ['TG', 'TGO', 'Togo', '228'],
  ['TK', 'TKL', 'Tokelau', '690'],
  ['TO', 'TON', 'Tonga', '676'],
  ['TT', 'TTO', 'Trinidad and Tobago', '1'],
  ['TN', 'TUN', 'Tunisia', '216'],
  ['TR', 'TUR', 'Türkiye (Turkey)', '90'],
  ['TM', 'TKM', 'Turkmenistan', '993'],
  ['TC', 'TCA', 'Turks and Caicos Islands', '1'],
  ['TV', 'TUV', 'Tuvalu', '688'],
  ['UG', 'UGA', 'Uganda', '256'],
  ['UA', 'UKR', 'Ukraine', '380'],
  ['AE', 'ARE', 'United Arab Emirates', '971'],
  ['GB', 'GBR', 'United Kingdom', '44'],
  ['US', 'USA', 'United States', '1'],
  ['UM', 'UMI', 'United States Minor Outlying Islands', '1'],
  ['UY', 'URY', 'Uruguay', '598'],
  ['UZ', 'UZB', 'Uzbekistan', '998'],
  ['VU', 'VUT', 'Vanuatu', '678'],
  ['VE', 'VEN', 'Venezuela', '58'],
  ['VN', 'VNM', 'Vietnam', '84'],
  ['VG', 'VGB', 'Virgin Islands (British)', '1'],
  ['VI', 'VIR', 'Virgin Islands (U.S.)', '1'],
  ['WF', 'WLF', 'Wallis and Futuna', '681'],
  ['EH', 'ESH', 'Western Sahara', '212'],
  ['YE', 'YEM', 'Yemen', '967'],
  ['ZM', 'ZMB', 'Zambia', '260'],
  ['ZW', 'ZWE', 'Zimbabwe', '263'],
];

/** Every country, `{ code, alpha3, name, dial }`, in alphabetical order of name. */
export const COUNTRIES = Object.freeze(TABLE
  .map(([code, alpha3, name, dial]) => Object.freeze({ code, alpha3, name, dial }))
  .sort((a, b) => a.name.localeCompare(b.name, 'en')));

/**
 * Every calling code once, lowest first: "+1", "+7", "+20" ... The phone field
 * offers codes, not countries, because several countries share one - a list of
 * countries showed a US number's "+1" as whichever of them came first.
 */
export const CALLING_CODES = Object.freeze([...new Set(COUNTRIES.map((country) => country.dial))]
  .sort((a, b) => Number(a) - Number(b))
  .map((dial) => `+${dial}`));

/** "+91", "91", "0091" -> "91": the digits a phone number's country code is sent as. */
export const callingCodeDigits = (value) => String(value ?? '').replace(/\D/g, '').replace(/^00/, '');

const BY_CODE = new Map(COUNTRIES.map((country) => [country.code, country]));
const ALPHA3 = new Set(COUNTRIES.map((country) => country.alpha3));

/** The country for a two-letter code, or null. */
export const countryByCode = (code) => BY_CODE.get(String(code ?? '').trim().toUpperCase()) ?? null;

/**
 * The three-letter code for a two-letter one, or a three-letter code as given
 * when it names a country. Null when it names none: a guessed nationality on a
 * passport record is a border problem, not a formatting one.
 */
export const toAlpha3 = (value) => {
  const raw = String(value ?? '').trim().toUpperCase();
  if (ALPHA3.has(raw)) return raw;
  return BY_CODE.get(raw)?.alpha3 ?? null;
};
